# Site settings
title: Christophe Gourmelon
subtitle: Full Stack JS Lead Developer & Release Manager
email: christophe@roparz.me
description: > # this means to ignore newlines until "baseurl:"
  Blog de Christophe Gourmelon.
  Full Stack JS Lead Developer & Release Manager.
baseurl: ""
url: "http://roparz.me"
twitter_username: roparz
github_username:  roparz

# Build settings
markdown: kramdown
